modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Mattzm2021/GunGale/issues"

[[mods]]
modId = "gungale"
version = "${file.jarVersion}"
displayName = "GunGale"
updateJSONURL = "https://raw.githubusercontent.com/Mattzm2021/GunGale/master/updates.json"
displayURL = "https://github.com/Mattzm2021/GunGale"
logoFile = "logo.png"
credits = "GunGale test group members"
authors = "Matthew Tseng"
description = '''
    A mod filled with weapons, excitements, and fun
'''

[[dependencies.gungale]]
modId = "jei"
mandatory = false
versionRange = "[7.7,7.8)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gungale]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gungale]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
